#pragma config(Motor,  port5,           gear1,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           gear2,         tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
		{
			motor[gear1] = vexRT[Ch3];
			motor[gear2] = vexRT[Ch3];
		}
}
