#pragma config(Motor,  port2,           ArmJoint1,     tmotorVex269, openLoop)
#pragma config(Motor,  port3,           ArmJoint2,     tmotorVex393, openLoop)
#pragma config(Motor,  port4,           Claw,          tmotorVex269, openLoop)
#pragma config(Motor,  port5,           ClawJoint,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port6,           Rotation,      tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard!!*//

task main()
{

	while(1==1)
	{
		motor[ArmJoint1] = vexRT(Ch2);//links the second arm joint to Channel 2 on the cortex
		motor[ArmJoint2] = vexRT(Ch3);//links the first arm joint to Channel 3 on the cortex

		if(vexRT(Btn5U) == 1) //If button 5U is pressed
		{
			if(vexRT(Btn6D) == 1)
			{
				motor[ClawJoint] = 40;//Then check if button 6U is pressed and then if so, speed up the motor.
			}
			else
			{
				motor[ClawJoint] = 20;
			}
			if(vexRT(Btn5U) == 0)
			{
				if(vexRT(Btn5D) == 1)//if button 5D is pressed
				{

					if(vexRT(Btn6U) == 1)
					{
						motor[ClawJoint] = -40;//Then check if button 6U is pressed and then if so, speed up the motor.
					}
					else
					{
						motor[ClawJoint] = -20;
					}
					if(vexRT(Btn5D) == 0)
					{
						motor[ClawJoint] = 0;
					}
					motor[Rotation] = vexRT(Ch1); //Rotation is channel 1
					motor[Claw] = vexRT(Ch4); //Claw is channel 4
				}
			}
		}
	}
}
