#pragma config(Motor,  port3,           wrist,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port4,           base,          tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           worm,          tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           belt,          tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           chain,         tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		wait1Msec(10);
		if((vexRT[Ch4] <= -10) || (vexRT[Ch4] >= 10)) { motor[base] = vexRT[Ch4]; }
		else { motor[base] = 0; }

		if((vexRT[Ch3] <= -10) || (vexRT[Ch3] >= 10)) { motor[worm] = vexRT[Ch3]; }
		else { motor[worm] = 0; }

		if((vexRT[Ch2] <= -10) || (vexRT[Ch2] >= 10)) { motor[belt] = vexRT[Ch2]; }
		else { motor[belt] = 0; }

		if(vexRT[Btn8U] == 1) { motor[chain] = 64; }
		if(vexRT[Btn8D] == 1) { motor[chain] = -64; }
		if(vexRT[Btn6U] == 1) { motor[chain] = 128; }
		if(vexRT[Btn6D] == 1) { motor[chain] = -128; }
		if((vexRT[Btn8D] == 0) && (vexRT[Btn8U] == 0) && (vexRT[Btn6D] == 0) && (vexRT[Btn6U] == 0)) { motor[chain] = 0; }
	}
}
