#pragma config(Sensor, in1,    pot,            sensorPotentiometer)
#pragma config(Sensor, dgtl1,  touch,          sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int i = 0;
int j = 0;
task main()
{
	while(true)
		{
			i = SensorValue(pot);
			j = SensorValue(touch);
		}



}
