#pragma config(Sensor, in1,    pot2,           sensorAnalog)
#pragma config(Sensor, in7,    pot,            sensorAnalog)
#pragma config(Sensor, dgtl1,  touch,          sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int potVar = 0;
int potVar2 = 0;
int j = 0;
task main()
{
	while(true)
		{
			potVar = SensorValue(pot);
			potVar2 = SensorValue(pot2);
			j = SensorValue(touch);
			wait1Msec(10);
		}



}
