#pragma config(Motor,  port2,           servo1,        tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int servoPosition = 0;
const int numberToIncrement = 2;
task main()
{
	while(true) {
		wait1Msec(100);
		if(vexRT(Btn5U) == 1) {
			servoPosition =+ numberToIncrement; // "var1=+ var 2" is the same thing as "var1 = var1 + var2", just shorter. Works with other operations as well (-, /, *)
		}
		motor[servo1] = servoPosition;
	}
}
